import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>suppléments musicaux</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* 
          <link rel="icon" href="/favicon.ico" /> 
          <meta name="description" content="Generated by create next app" />
        */}
      </Head>

      <main>
        <h1>suppléments musicaux</h1>

        <p>bester Chor</p>
      </main>
    </>
  )
}
